// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PGDatabaseContext.GeneratedDatabase;

#nullable disable

namespace PGDatabaseContext.Migrations
{
    [DbContext(typeof(PgIndexerContext))]
    [Migration("20241211201300_testmetadatainpaths2")]
    partial class testmetadatainpaths2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PGDatabaseContext.GeneratedDatabase.paths", b =>
                {
                    b.Property<byte[]>("path_key")
                        .HasColumnType("bytea");

                    b.Property<DateTime?>("created_on")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("deleted_on")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("etag")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("filesystem_name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime?>("last_modified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("metadata_json")
                        .HasColumnType("jsonb");

                    b.Property<string>("path")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<string>("path_reversed")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasComputedColumnSql("reverse((path)::text)", true);

                    b.Property<bool>("should_update_metadata")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.HasKey("path_key")
                        .HasName("paths_pk");

                    b.HasIndex(new[] { "filesystem_name", "path" }, "filesystem_path_unique")
                        .HasAnnotation("Npgsql:StorageParameter:deduplicate_items", "true");

                    b.ToTable("paths");

                    b.HasAnnotation("Npgsql:StorageParameter:autovacuum_enabled", "true");
                });

            modelBuilder.Entity("PGDatabaseContext.GeneratedDatabase.paths_metadata", b =>
                {
                    b.Property<byte[]>("path_key")
                        .HasColumnType("bytea");

                    b.Property<string>("etag")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("metadata_json")
                        .HasColumnType("jsonb");

                    b.HasKey("path_key")
                        .HasName("paths_metadata_pk");

                    b.ToTable("paths_metadata");
                });
#pragma warning restore 612, 618
        }
    }
}
